SELECT TABLE_CATALOG, TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'public' and TABLE_NAME LIKE '%%' 
ORDER BY TABLE_NAME ASC; --DESC

SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'produtor' 
ORDER BY ORDINAL_POSITION ASC --DESC